language: java
jdk: openjdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper"
script:
- "./gradlew distTar"
install: true

deploy:
  provider: releases
  api_key:
    secure: kVaLM+TgE5cVFcT7ZIFmVXTGTDJ9LWyLPiJkXEL98LyxrEqJCjkqwFCxT20EbjyMnReobYNq3Ny7W6iNT4pMyGuo63ndtwuS+LDK+JK1sG0vNrsC4+GYq2ZT07/DzcvloxrFD2aNQ3dSs0lkjG/j9v18LASanfr/Z4edN2mAUg+NMmh+KZ9HOapjwNczHCSQYM7zGrhWwP/+ahcfTUrixaEcoQkb8oXS96kBv1tV6wVKPRo/LVapbJlHTwPNvRIbX3Tv//2d/76LrNDLQBEX8ucDg0p7OgHCrmw9uabi2nJpC8rc/HLfLaUNeU1rPom212v9k6gHLTzm2P2ekOroNvfWi3Iuwt+AEzNZ8quylpuQFCXGlmOLSPoWb9p9F6+Dkziy4I9VYQUlkkmcSPm+E+fQQVd39b0somUu1797Q60lJWmpadvhRvuzr7PlluXpDK1MbLAvsoCvGvlWzf+GeMVTnS/m0Pw6bIze8uq8yNojxNYeKLpgiVKX/oAbJqMgB3JZ7v9qSQmxOJF9AoZneJ0p/102LH7Pm+eaZ6Q2VCtlRuiwW2ALWsXFETpDN27duNf0zPz+g3odH7grWssJNKj126yIA1v6L4mOZTds0oyf2NGGWGm0GHbmTiOmKaxwOwtczxmF7QDhjTSoM0ZjfyjDaThoo+iHwOs+HLAvGaw=
  skip_cleanup: true
  file_glob: true
  file: build/distributions/portal-client-*.tar.gz
  draft: false
  overwrite: true
  on:
    tags: true
